name: Build and Test

on: 
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  FormattingLint: 
    runs-on: macos-15
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: SwiftFormat
        run: echo swiftformat --lint `git diff --name-only HEAD^1 HEAD` --reporter github-actions-log

  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: norio-nomura/action-swiftlint@9f4dcd7fd46b4e75d7935cf2f4df406d5cae3684 # 3.2.1
        env:
          args: --strict
          DIFF_BASE: ${{ github.base_ref }}
  iOS:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: 16.4
    - name: Install Homebrew kegs
      run: make setup-brew
    - name: Build for iOS
      run: make build-for-testing-ios
    - name: Test for iOS
      run: make test-without-building-ios

